{% set version = "0.3" %}
{% set name = "cibots" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/ci-bots/archive/{{ version }}.tar.gz
    sha256: 2177f3035689147ab74f0ab07bc6b1700052bcbd2f3fdcb498a3e3e57b9622e1

build:
  number: 1002
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  source_files:
    - run_tests.py
  commands:
    - python run_tests.py -v2

about:
    home:  http://github.com/UV-CDAT/ci-bots
    license: BSD 3-clause
    license_file: LICENCE.txt
    summary: 'Continuous Integration Tools'

extra:
  recipe-maintainers:
    - doutriaux1
