travis:
  secure:
    BINSTAR_TOKEN: LCRPcVgNQQcnnmk75hhrXFefpcyucMbcENMYHDlORLkudt+SVHJUIZ/3ceyZA1SlpLLK817TcbJgDcCqwrXys6uPp+Y42sW1Hid/8/wdwoa7E5yDJRLPocQp7t1ud+uw88WqOviJahoOJ1O/cY44CPl6diaiZysL55rFyyV3Ho/y6wGHWSSjkGfhLjwdwkc66P+By84ERr60KIEOA9quIGZEYAAuT0dxo/+adzrPqPz0AUe+1+v8utQR14oSgLY6v4Y+Cugo0ZkWXvMRE2m8p4GwgOufa3Dc17QJNEoUzcK3ngHUkrosxFNvWSgFvVvEgToPhBGxXd735aqpE/RnXWaKZZi6NYhJaDMHbSR4fE4fBmfIdm3DM4Ux0cVRZ827Z1HLbBdu8HN/OrvW1FsYBLNmYehF8bcIQMWJiLoGTrXT/SjAccLkWmgAXWVbZmDH5ZfQHkUlICSkTOyEero8u6FqHJVjMMzBBdR+gpgtG/bQKaORvIjSNXrWduX9mka2nfwQciX/fAYc7akc5tZaRfKzssP9ouKwcY7gTd+mjMX5PCOZLpV8Aaql+N+eF3pDVfuB+g2kD+O902/7YS22Pd/TnffaxGjwXmt+WERIWTBxlQU8P7ekaofyMe4Asta6HiWUJgslYZ6noxkxMI6iK2BKx1wXORkBUJw7wI6Mk10=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
