travis:
  secure:
    BINSTAR_TOKEN: uw6havL81jEknM5sHnD7nPS7z1afRZugWmNMW7r5dOlVRkE/in7OiNOyAoBSa2zGlX9T0KCMgjfh/fIYw54SF3UEeHqfSvGgkORPEavVd6P9K3ogy6L8N9TU/pUcJ19ql15EgeW4jU8waFcZY0X7ZQg2Wale9olkVvvz/+KpPQ7DVZANAQUv0T76zHdUcDFJ1eedEBOL3UWVadW2l1DPOAlGPnsDWYnwYuKMfMfg0VAfTmCfkpKSdWl7VGwWjaaoeXnmnM2+7AnhMfU8PL2OuoQrmqV8oQSR7jWOei2kYkzUAwmaAFxku2K0zwGBRsrh4xEOvGxorOyxIOlHol2KyQRs9KSbB+DxIS06QID2bgFRhZ7F4JxhwtXJmu6zam9AV7R4JSz+ZKpEyJ+okN4MU2BDfSaS7eCQtM9RuuktKshxgymyTYvK9sLzLAkWqQ0KPgN87Cg1/1H1ZyhAmmOK81U2A4t+qFhZNcT1cBPVRifgq7ali3RM9ZguG9P8JjyEqrwHcTeaPM5iHDSIoCqHMNLm6YXQ4K48ZkbOCON/AI/NJZgju1gsilQOQE+exWk4NgyRgaPxiOQ1eJAlDYeAH90RKG/L+GJ2ga48PEf3b0xtTIVfX92iOhuQ3QgvKs1GZM7qsa1K3kPw/lNSbHo28cjnpbakeJehO3a5SugbAys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
